name: lodart
description: Lodart is a Dart utility library like lodash and aims to implement utilities to make Dart easier to use and keep similar naming styles to lodash.
version: 0.3.0
repository: https://github.com/KiritaniAyaka/lodart

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
