name: lodart
description: Lodart is a dart utility library like lodash.
version: 0.1.0
repository: https://github.com/KiritaniAyaka/lodart

environment:
  sdk: ^3.2.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
