name: Dart

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  Lint-and-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart pub global activate coverage
      - name: Testing and coverage
        run: dart pub global run coverage:test_with_coverage
      - name: Upload coverage result
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: unittests
          name: lodart-unittest
          verbose: true
